### ISSUE TITLE
TypeError: no implicit conversion of Symbol into Integer

### ISSUE THREAD

**Issue by keo** [mashiro/saorin-server-reel#1]
Hi,

trying the example in README I get this:

```
E, [2015-01-01T21:51:24.363206 #42898] ERROR -- : Actor crashed!
TypeError: no implicit conversion of Symbol into Integer
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/reel-0.5.0/lib/reel/server.rb:23:in `[]'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/reel-0.5.0/lib/reel/server.rb:23:in `initialize'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
E, [2015-01-01T21:51:24.363424 #42898] ERROR -- : Actor crashed!
TypeError: no implicit conversion of Symbol into Integer
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/reel-0.5.0/lib/reel/server.rb:23:in `[]'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/reel-0.5.0/lib/reel/server.rb:23:in `initialize'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
    (celluloid):0:in `remote procedure call'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid.rb:180:in `new_link'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/supervision_group.rb:141:in `start'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/supervision_group.rb:129:in `initialize'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/supervision_group.rb:85:in `new'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/supervision_group.rb:85:in `add'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/supervision_group.rb:72:in `supervise'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in `dispatch'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
W, [2015-01-01T21:51:24.364593 #42898]  WARN -- : Terminating task: type=:call, meta={:method_name=>:initialize}, status=:callwait
    Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
/opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:34:in `terminate': task was terminated (Celluloid::Task::TerminatedError)
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `each'
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:321:in `handle_crash'
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:166:in `rescue in run'
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:148:in `run'
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'
    from (celluloid):0:in `remote procedure call'
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:92:in `value'
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/proxies/cell_proxy.rb:17:in `_send_'
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid.rb:169:in `new'
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid/supervisor.rb:10:in `supervise'
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/celluloid-0.16.0/lib/celluloid.rb:188:in `supervise'
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/saorin-server-reel-0.1.1/lib/saorin/server/reel.rb:21:in `start'
    from /opt/rubies/2.0.0-p451/lib/ruby/gems/2.0.0/gems/saorin-0.6.0/lib/saorin/server.rb:17:in `start'
    from lib/rpc_server.rb:23:in `<main>'
```

Any ideas why this won't work?

I am using ruby 2.0.0.

**Comment by mashiro** [comment]
It was broken by the change of reel v0.5.0.
Now fixed and released saorin-server-reel v0.2.0.
Please try it.
